from string_search import boyer_moore
text = '''NNNNNNNNNNNNNNNNNNNGNNNNCCNTGANNTACNCNNNNNGNNNCGGANTGANCNNNAGNACACTGAAAGAGCACTCG
GCGCTAGCAGTGATGACAAGCAAGTCTGGCACTNAACGCGCGCAGCGAACAGGAGTAGTAGACGCGCCGACTTACTCTGC
ACCTGCAGGTCCATCTCGCGCATTTCCGTGAAGCGGTCCCGCAGATCCATAGGAAGCTGCTCAATCACTGTCAAAGGGAG
AGTCCGTCAGAGGGGCGGGGCCAACGGCGAAATACGCGCTTACGTCACTGCGCGCGTGCGTCAGGGGGGTCGAGGGGGCC
GGCAGCCCACAACGAGGCTGCCAGTTACCGTGAGAAAGAAACATCCCCCGCCGCCCCCTCCCTCCCGCCATCTCGCTGCC
CGTCGTCTCACGCTCTTGCCCGCCCGCACGTCCCACTGGCGGCCGCCGCCAGCGCCGCGCACTCACTTTCCAGATAGTCT
TCTAGGTACAACATCNCGGCCCTTAGAGCTGAGGGAACGAGGGGGTCCAGGGGTTTATTTGTGTCACTCGCTGTCNCCGG
AGTNNTGTCCCCTCCAATATGGCGCCTCCGCTAGCANCACCCGCTCGACTCCGGCAAAANAAAAAANGAAAAAAAAAAAA
NAGNNTTTTAGGGCCAGGNNCGCCTGACNNANNTGAGACCNNNNNGGNNNNGNNNNNNANAGAAAAACCATGGCCCCGAC
GGGTGTCNCNCCCCTGNNCTNNGTCGNNATGNGNGTAGCGGCGTNTTNTGTCNNNCTNCNNNANGNGNNNNNGNNNNNNNNNTCCCTGC
GGCANNNCNACNNNNNNNNNTNNCNTGNTNANCGTGCNNNNNNNANTNNNANNGNNNNNCCCNNGTTTNTTTGNNNANTT
TNNNNNNANNNGCNGTAGCGGCGNNNNTTNNNNNNNNNN'''
patt = 'GTAGCGGCG'
match_obj = boyer_moore.badChar_goodSufixRuls(patt)
print('skipTable')
print(match_obj.skipTable)
print("-------------------------------------")
print('good Suffix Dictionary')
print(match_obj.goodSuffixData)
print("-------------------------------------")
print(match_obj.findMatch(text))
