from boyer_moore_algorithm import boyer_moore
text = '''NNNNNNNNNNNNNNNNNNNGNNNNCCNTGANNTACNCNNNNNGNNNCGGANTGANCNNNAGNACACTGAAAGAGCACTCG
GCGCTAGCAGTGATGACAAGCAAGTCTGGCACTNAACGCGCGCAGCGAACAGGAGTAGTAGACGCGCCGACTTACTCTGC
ACCTGCAGGTCCATCTCGCGCATTTCCGTGAAGCGGTCCCGCAGATCCATAGGAAGCTGCTCAATCACTGTCAAAGGGAG
AGTCCGTCAGAGGGGCGGGGCCAACGGCGAAATACGCGCTTACGTCACTGCGCGCGTGCGTCAGGGGGGTCGAGGGGGCC
GGCAGCCCACAACGAGGCTGCCAGTTACCGTGAGAAAGAAACATCCCCCGCCGCCCCCTCCCTCCCGCCATCTCGCTGCC
CGTCGTCTCACGCTCTTGCCCGCCCGCACGTCCCACTGGCGGCCGCCGCCAGCGCCGCGCACTCACTTTCCAGATAGTCT
TCTAGGTACAACATCNCGGCCCTTAGAGCTGAGGGAACGAGGGGGTCCAGGGGTTTATTTGTGTCACTCGCTGTCNCCGG
AGTNNTGTCCCCTCCAATATGGCGCCTCCGCTAGCANCACCCGCTCGACTCCGGCAAAANAAAAAANGAAAAAAAAAAAA
NAGNNTTTTAGGGCCAGGNNCGCCTGACNNANNTGAGACCNNNNNGGNNNNGNNNNNNANAGAAAAACCATGGCCCCGAC
GGGTGTCNCNCCCCTGNNCTNNGTCGNNATGNGNGTAGCGGCGTNTTNTGTCNNNCTNCNNNANGNGNNNNNGNNNNNNNNNTCCCTGC
GGCANNNCNACNNNNNNNNNTNNCNTGNTNANCGTGCNNNNNNNANTNNNANNGNNNNNCCCNNGTTTNTTTGNNNANTT
TNNNNNNANNNGCNGTAGCGGCGNNNNTTNNNNNNNNNN'''
pattern = 'GTAGCGGCG'
match_obj = boyer_moore.badChar_goodSufixRuls(pattern)
print('skipTable\n',match_obj.skipTable)
print("-------------------------------------")
print('goodSuffixData\n',match_obj.goodSuffixData)
print("-------------------------------------")
print('index first matches\n',match_obj.findMatch(text))
for match in match_obj.findMatch(text):
    print(text[match:match+len(pattern)])

# Output:
skipTable
   G_8 C_7 G_6 G_5 C_4 G_3 A_2 T_1 G_0
A   5   4   3   2   1   0   -   1   0
T   6   5   4   3   2   1   0   -   0
C   0   -   1   0   -   3   2   1   0
G   -   0   -   -   0   -   1   0   -
goodSuffixData
 {'G': 1, 'CG': 2, 'GCG': 2, 'GGCG': 7, 'CGGCG': 7, 'GCGGCG': 7, 'AGCGGCG': 7, 'TAGCGGCG': 7, 'GTAGCGGCG': 7}
index first matches
 [763, 899]
GTAGCGGCG
GTAGCGGCG
